### PR TITLE
image/webp

### PR DESCRIPTION
**Pull request by motiejus**
support `image/webp`

Refs https://github.com/openstreetmap/mod_tile/pull/318

### CODE REVIEW

**Comment by motiejus** [comment]
Hm, there seems to be a footgun: renderd will return only the image that was configured, and it accepts only a single image format. So it is invalid to ask for both `.png` and `.webp` - the payload will be of the type in the renderd config:

```
motiejus@fwmine:~$ wget http://localhost:8080/tile/19/298976/166646.png
--2023-06-05 01:48:02--  http://localhost:8080/tile/19/298976/166646.png
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9032 (8.8K) [image/png]
Saving to: ‘166646.png’

166646.png                              100%[==============================================================================>]   8.82K  --.-KB/s    in 0s      

2023-06-05 01:48:02 (228 MB/s) - ‘166646.png’ saved [9032/9032]

motiejus@fwmine:~$ wget http://localhost:8080/tile/19/298976/166646.webp
--2023-06-05 01:48:05--  http://localhost:8080/tile/19/298976/166646.webp
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9032 (8.8K) [image/webp]
Saving to: ‘166646.webp’

166646.webp                             100%[==============================================================================>]   8.82K  --.-KB/s    in 0s      

2023-06-05 01:48:05 (210 MB/s) - ‘166646.webp’ saved [9032/9032]

motiejus@fwmine:~$ file 166646.*
166646.png:  RIFF (little-endian) data, Web/P image
166646.webp: RIFF (little-endian) data, Web/P image
motiejus@fwmine:~$ ls -l 166646.*
-rw-r--r-- 1 motiejus motiejus 9032 Jun  5 01:13 166646.png
-rw-r--r-- 1 motiejus motiejus 9032 Jun  5 01:13 166646.webp
```

**Comment by nielsole** [comment]
probably makes sense to wait for https://github.com/openstreetmap/mod_tile/pull/318 to be merged, right?

**Comment by motiejus** [comment]
> probably makes sense to wait for [openstreetmap/mod_tile#318](https://github.com/openstreetmap/mod_tile/pull/318) to be merged, right?

Indeed, correct. Converted to draft.

**Comment by hummeltech** [comment]
Alright, that PR has been merged.

**Review by nielsole — APPROVED** [review]

**Comment by nielsole** [comment]
motiejus, do you want to change anything or merge as is?

**Comment by motiejus** [comment]
> motiejus, do you want to change anything or merge as is?

I am not proud of it, as it makes truly minimal adjustments to make webp possible. But it's not horrible, so we can land it.

**Pull request merged**
